name: HaitiCSS
markdown: kramdown

gems: ['jekyll-github-metadata']
repository: haiticss/haiticss.github.io

title: HaitiCSS
url: https://haiticss.io
enforce_ssl: haiticss.io

# HaitiCSS core path
haiticss-path: ../_includes/haiticss/

# Google services
google_analytics: UA-97633338-1

# Collections
collections:
  docs-foundations:
    label: foundations
    output: true
    permalink: /docs/foundations/:name
  docs-objects:
    label: objects
    output: true
    permalink: /docs/objects/:name
  docs-tools:
    label: tools
    output: true
    permalink: /docs/tools/:name
  haiticss:
    output: false